name: DEV

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Configure the API
      run: |
        echo "SOME_PARAM=VALUE" > .env
        echo "DB_PASSWORD=$DB_PASSWORD" >> ./.env

    - name: Deploy the API, and DB
      run: |
        docker-compose up -d --force-recreate --build
